enum CHandlingAttrib
{
	HANDL_IDENTIFIER = 1, // A
	HANDL_FMASS,	// B
	HANDL_FTURNMASS, // c
	HANDL_FDRAGMULTIPLIER, // D
	HANDL_CENTREOFMASS_X,	// F
	HANDL_CENTREOFMASS_Y,	// G
	HANDL_CENTREOFMASS_Z,	// H
	HANDL_NPERCENTSUBMERGED,	// I
	HANDL_FTRACTIONMULTIPLIER,	// J
	HANDL_FTRACTIONLOSS,	// K
	HANDL_FTRACTIONBIAS,	// L
	HANDL_TR_NNUMBEROFGEARS,	// M // transmission data, full name is too long for pawn
	HANDL_TR_FMAXVELOCITY,	// N
	HANDL_TR_FENGINEACCELERATION,	// O
	HANDL_TR_FENGINEINERTIA,	// P
	HANDL_TR_NDRIVETYPE,	// Q
	HANDL_TR_NENGINETYPE,	// R
	HANDL_FBRAKEDECELERATION,	// S
	HANDL_FBRAKEBIAS,	// T
	HANDL_BABS,	// U
	HANDL_FSTEERINGLOCK,	// V
	HANDL_FSUSPENSIONFORCELEVEL,	// a
	HANDL_FSUSPENSIONDAMPINGLEVEL,	// b
	HANDL_FSUSPENSIONHIGHSPDCOMDAMP,	// c
	HANDL_FSUSPENSIONUPPERLIMIT,	// d
	HANDL_FSUSPENSIONLOWERLIMIT,	// e
	HANDL_FSUSPENSIONBIAS,	// f
	HANDL_FSUSPENSIONANTIDIVEMULT,	// g
	HANDL_FSEATOFFSETDISTANCE,	// aa
	HANDL_FCOLLISIONDAMAGEMULT,	// ab
	HANDL_IMONETARYVALUE,	// ac
	HANDL_MODELFLAGS,	// af
	HANDL_HANDLINGFLAGS,	// ag
	HANDL_FRONTLIGHTS,	// ah
	HANDL_REARLIGHTS,	// ai
	HANDL_ANIMGROUP	 // aj
};

enum CHandlingAttribType
{
	TYPE_NONE,
	TYPE_INT,
	TYPE_FLOAT,
	TYPE_BYTE,
	TYPE_FLAG
};

CHandlingAttribType GetHandlingAttribType(CHandlingAttrib attribute)
{
	switch(attribute)
	{
	case HANDL_FMASS:
		case HANDL_FDRAGMULTIPLIER:
		case HANDL_CENTREOFMASS_X:
		case HANDL_CENTREOFMASS_Y:
		case HANDL_CENTREOFMASS_Z:
		case HANDL_FTRACTIONMULTIPLIER:
		case HANDL_FTRACTIONLOSS:
		case HANDL_FTRACTIONBIAS:
		case HANDL_TR_FMAXVELOCITY:
		case HANDL_TR_FENGINEACCELERATION:
		case HANDL_TR_FENGINEINERTIA:
		case HANDL_FBRAKEDECELERATION:
		case HANDL_FBRAKEBIAS:
		case HANDL_FSTEERINGLOCK:
		case HANDL_FSUSPENSIONFORCELEVEL:
		case HANDL_FSUSPENSIONDAMPINGLEVEL:
		case HANDL_FSUSPENSIONHIGHSPDCOMDAMP:
		case HANDL_FSUSPENSIONUPPERLIMIT:
		case HANDL_FSUSPENSIONLOWERLIMIT:
		case HANDL_FSUSPENSIONBIAS:
		case HANDL_FSUSPENSIONANTIDIVEMULT:
		case HANDL_FSEATOFFSETDISTANCE:
		case HANDL_FCOLLISIONDAMAGEMULT:
			return TYPE_FLOAT;

		case HANDL_NPERCENTSUBMERGED:
		case HANDL_ANIMGROUP:
		case HANDL_FRONTLIGHTS:
		case HANDL_REARLIGHTS:
		case HANDL_TR_NDRIVETYPE:
		case HANDL_TR_NENGINETYPE:
		case HANDL_TR_NNUMBEROFGEARS:
			return TYPE_BYTE;

		case HANDL_IDENTIFIER:
		case HANDL_IMONETARYVALUE:
			return TYPE_INT;

		case HANDL_HANDLINGFLAGS:
		case HANDL_MODELFLAGS:
			return TYPE_FLAG;
	}
	return TYPE_NONE;
}